import path from "node:path";
import fs from "fs-extra";
import { confirm, intro, isCancel, outro, select, text } from "@clack/prompts";
import pc from "picocolors";

import { loadConfig, writeConfig } from "../utils/config.js";
import type { FastlaneConfig } from "../types.js";

interface FastlaneSetupOptions {
  cwd?: string;
  force?: boolean;
}

function unwrap<T>(value: T | symbol): T {
  if (isCancel(value)) {
    throw new Error("cancelled-by-user");
  }
  return value;
}

function makeFastfile(config: FastlaneConfig): string {
  const androidLane = config.android?.lane ?? "upload_store";
  const androidTrack = config.android?.defaultTrack ?? "internal";
  const iosLane = config.ios?.lane ?? "upload_store";
  const iosTrack = config.ios?.defaultTrack ?? "testflight";

  return [
    '# Fastfile generated by react-native-build-helper',
    '# Customize lanes as needed for your release process.',
    '',
    "default_platform(:android)",
    '',
    "platform :android do",
    `  desc \"Upload Android artifact to Google Play (default track: ${androidTrack})\"`,
    `  lane :${androidLane} do |options|`,
    `    track_name = options[:track] || \"${androidTrack}\"`,
    "    artifact_type = options[:artifact_type]",
    "    artifact_path = options[:artifact_path]",
    "",
    "    supply_options = {",
    "      track: track_name,",
    "      skip_upload_metadata: true,",
    "      skip_upload_images: true,",
    "      skip_upload_screenshots: true",
    "    }",
    "",
    "    if artifact_path && !artifact_path.to_s.empty?",
    "      normalized = artifact_path.to_s.downcase",
    "      if artifact_type.to_s == \"aab\" || normalized.end_with?(\".aab\")",
    "        supply_options[:aab] = artifact_path",
    "      else",
    "        supply_options[:apk] = artifact_path",
    "      end",
    "    end",
    "",
    "    supply(supply_options)",
    "  end",
    "end",
    '',
    "platform :ios do",
    `  desc \"Upload iOS build (default destination: ${iosTrack})\"`,
    `  lane :${iosLane} do |options|`,
    `    destination = options[:track] || \"${iosTrack}\"`,
    "    artifact_path = options[:artifact_path]",
    "",
    "    if destination == \"app_store\"",
    "      deliver_options = {",
    "        submit_for_review: false,",
    "        automatic_release: false,",
    "        skip_metadata: true,",
    "        skip_screenshots: true",
    "      }",
    "      deliver_options[:ipa] = artifact_path if artifact_path && !artifact_path.to_s.empty?",
    "      deliver(deliver_options)",
    "    else",
    "      pilot_options = { skip_waiting_for_build_processing: true }",
    "      pilot_options[:ipa] = artifact_path if artifact_path && !artifact_path.to_s.empty?",
    "      pilot(pilot_options)",
    "    end",
    "  end",
    "end",
    ""
  ].join("\n");
}

function makeAppfile(config: FastlaneConfig): string {
  const lines: string[] = ["# Appfile generated by react-native-build-helper"];

  if (config.ios?.appIdentifier) {
    lines.push(`app_identifier(\"${config.ios.appIdentifier}\")`);
  }
  if (config.android?.packageName) {
    lines.push(`package_name(\"${config.android.packageName}\")`);
  }
  if (config.ios?.appleId) {
    lines.push(`apple_id(\"${config.ios.appleId}\")`);
  }
  if (config.ios?.teamId) {
    lines.push(`team_id(\"${config.ios.teamId}\")`);
  }

  lines.push("");
  return lines.join("\n");
}

async function maybePromptWithDefault(message: string, defaultValue: string): Promise<string> {
  const value = await text({ message, defaultValue });
  return String(unwrap(value)).trim();
}

export async function runFastlaneSetupCommand(options: FastlaneSetupOptions): Promise<void> {
  const projectDir = options.cwd ? path.resolve(options.cwd) : process.cwd();
  const config = await loadConfig(projectDir);

  try {
    intro(pc.bold(pc.cyan("RN Build Helper Fastlane Setup")));

    const useAndroid = Boolean(
      unwrap(
        await confirm({
          message: "Configure Android Fastlane upload lane?",
          initialValue: true
        })
      )
    );

    const useIos = Boolean(
      unwrap(
        await confirm({
          message: "Configure iOS Fastlane upload lane?",
          initialValue: true
        })
      )
    );

    if (!useAndroid && !useIos) {
      outro(pc.yellow("No platform selected. Setup cancelled."));
      return;
    }

    const nextFastlaneConfig: FastlaneConfig = {
      ...(config.fastlane ?? {})
    };

    if (useAndroid) {
      const lane = await maybePromptWithDefault(
        "Android lane name",
        config.fastlane?.android?.lane ?? "upload_store"
      );
      const track = unwrap(
        await select({
          message: "Default Android track",
          options: [
            { value: "internal", label: "internal" },
            { value: "alpha", label: "alpha" },
            { value: "beta", label: "beta" },
            { value: "production", label: "production" }
          ],
          initialValue: config.fastlane?.android?.defaultTrack ?? "internal"
        })
      ) as string;
      const packageName = await maybePromptWithDefault(
        "Android package name (applicationId)",
        config.fastlane?.android?.packageName ?? ""
      );

      nextFastlaneConfig.android = {
        lane: lane || "upload_store",
        defaultTrack: track,
        packageName: packageName || undefined
      };
    }

    if (useIos) {
      const lane = await maybePromptWithDefault(
        "iOS lane name",
        config.fastlane?.ios?.lane ?? "upload_store"
      );
      const track = unwrap(
        await select({
          message: "Default iOS destination",
          options: [
            { value: "testflight", label: "testflight" },
            { value: "app_store", label: "app_store" }
          ],
          initialValue: config.fastlane?.ios?.defaultTrack ?? "testflight"
        })
      ) as string;
      const appIdentifier = await maybePromptWithDefault(
        "iOS app identifier (bundle id)",
        config.fastlane?.ios?.appIdentifier ?? ""
      );
      const appleId = await maybePromptWithDefault(
        "Apple ID (optional)",
        config.fastlane?.ios?.appleId ?? ""
      );
      const teamId = await maybePromptWithDefault(
        "Apple team ID (optional)",
        config.fastlane?.ios?.teamId ?? ""
      );

      nextFastlaneConfig.ios = {
        lane: lane || "upload_store",
        defaultTrack: track,
        appIdentifier: appIdentifier || undefined,
        appleId: appleId || undefined,
        teamId: teamId || undefined
      };
    }

    const fastlaneDir = path.join(projectDir, "fastlane");
    const fastfilePath = path.join(fastlaneDir, "Fastfile");
    const appfilePath = path.join(fastlaneDir, "Appfile");

    await fs.ensureDir(fastlaneDir);

    const fastfileExists = await fs.pathExists(fastfilePath);
    const appfileExists = await fs.pathExists(appfilePath);

    if (!options.force && (fastfileExists || appfileExists)) {
      const shouldOverwrite = Boolean(
        unwrap(
          await confirm({
            message: "Fastlane files already exist. Overwrite Fastfile/Appfile?",
            initialValue: false
          })
        )
      );
      if (!shouldOverwrite) {
        config.fastlane = nextFastlaneConfig;
        await writeConfig(projectDir, config);
        outro(pc.green("Saved Fastlane settings in .rnbuildrc.yml without overwriting existing Fastlane files."));
        return;
      }
    }

    await fs.writeFile(fastfilePath, makeFastfile(nextFastlaneConfig), "utf8");
    await fs.writeFile(appfilePath, makeAppfile(nextFastlaneConfig), "utf8");

    config.fastlane = nextFastlaneConfig;
    await writeConfig(projectDir, config);

    const hasGemfile = await fs.pathExists(path.join(projectDir, "Gemfile"));
    console.log(pc.gray(`Fastlane directory: ${fastlaneDir}`));
    console.log(pc.gray(`Fastfile: ${fastfilePath}`));
    console.log(pc.gray(`Appfile: ${appfilePath}`));
    console.log(
      pc.gray(
        hasGemfile
          ? "Use bundle exec fastlane for best consistency."
          : "Tip: add a Gemfile and install fastlane for reproducible CI runs."
      )
    );

    outro(pc.bold(pc.green("Fastlane setup complete.")));
  } catch (error) {
    if (error instanceof Error && error.message === "cancelled-by-user") {
      outro(pc.yellow("Fastlane setup cancelled."));
      return;
    }
    throw error;
  }
}
