// Auto-generated by react-native-build-orchestrator. Import this file in your app code.
import RNBuildEnv from "../../rnbuild.env";
export { RNBuildEnv };
export type { RNBuildEnvKey } from "../../rnbuild.env";
const Config = RNBuildEnv;
export default Config;
