import path from "node:path";
import fs from "fs-extra";

import type { BuildType, Platform } from "../types.js";

export function createRuntimeVars(params: {
  envName: string;
  buildType?: BuildType;
  platform?: Platform;
  flavor?: string;
  envFileVars: Record<string, string>;
  envConfigVars: Record<string, string>;
}): Record<string, string> {
  const buildType = params.buildType ?? "development";

  return {
    ...params.envFileVars,
    ...params.envConfigVars,
    NODE_ENV: buildType === "development" ? "development" : "production",
    RNBUILD_ENV_NAME: params.envName,
    RNBUILD_BUILD_TYPE: buildType,
    RNBUILD_PLATFORM: params.platform ?? "auto",
    RNBUILD_FLAVOR: params.flavor ?? ""
  };
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function toAndroidResourceSuffix(key: string): string {
  const normalized = key
    .toLowerCase()
    .replace(/[^a-z0-9_]/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_+|_+$/g, "");
  return normalized || "value";
}

function makeInfoPlistKey(key: string): string {
  const normalized = key
    .toUpperCase()
    .replace(/[^A-Z0-9_]/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_+|_+$/g, "");
  return `RNBUILD_${normalized || "VALUE"}`;
}

async function writeAndroidNativeEnv(projectDir: string, vars: Record<string, string>): Promise<{
  androidJsonPath: string;
  androidXmlPath: string;
} | null> {
  const appDir = path.join(projectDir, "android", "app");
  if (!(await fs.pathExists(appDir))) {
    return null;
  }

  const assetsDir = path.join(appDir, "src", "main", "assets");
  await fs.ensureDir(assetsDir);
  const androidJsonPath = path.join(assetsDir, "rnbuild_env.json");
  await fs.writeFile(androidJsonPath, `${JSON.stringify(vars, null, 2)}\n`, "utf8");

  const valuesDir = path.join(appDir, "src", "main", "res", "values");
  await fs.ensureDir(valuesDir);
  const androidXmlPath = path.join(valuesDir, "rnbuild_env.xml");

  const xmlLines = [
    "<?xml version=\"1.0\" encoding=\"utf-8\"?>",
    "<!-- Auto-generated by react-native-build-orchestrator. Do not edit manually. -->",
    "<resources>"
  ];

  for (const [key, value] of Object.entries(vars)) {
    const name = `rnbuild_env_${toAndroidResourceSuffix(key)}`;
    xmlLines.push(`  <string name=\"${name}\">${escapeXml(value)}</string>`);
  }
  xmlLines.push("</resources>");

  await fs.writeFile(androidXmlPath, `${xmlLines.join("\n")}\n`, "utf8");
  return { androidJsonPath, androidXmlPath };
}

function injectInfoPlistBlock(content: string, vars: Record<string, string>): string {
  const start = "<!-- RNBUILD_ENV_START -->";
  const end = "<!-- RNBUILD_ENV_END -->";
  const existingBlock = new RegExp(`${escapeRegExp(start)}[\\s\\S]*?${escapeRegExp(end)}\\n?`, "g");
  let updated = content.replace(existingBlock, "");

  const blockLines = [start];
  for (const [key, value] of Object.entries(vars)) {
    blockLines.push(`\t<key>${makeInfoPlistKey(key)}</key>`);
    blockLines.push(`\t<string>${escapeXml(value)}</string>`);
  }
  blockLines.push(end);
  const block = `${blockLines.join("\n")}\n`;

  const closeIndex = updated.lastIndexOf("</dict>");
  if (closeIndex === -1) {
    return updated;
  }

  return `${updated.slice(0, closeIndex)}${block}${updated.slice(closeIndex)}`;
}

async function collectInfoPlistPaths(dir: string): Promise<string[]> {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const files: string[] = [];

  for (const entry of entries) {
    if (entry.name === "Pods" || entry.name === "build" || entry.name === ".symlinks") {
      continue;
    }

    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      const nested = await collectInfoPlistPaths(fullPath);
      files.push(...nested);
      continue;
    }

    if (entry.isFile() && entry.name === "Info.plist") {
      files.push(fullPath);
    }
  }

  return files;
}

async function writeIosNativeEnv(projectDir: string, vars: Record<string, string>): Promise<string[]> {
  const iosDir = path.join(projectDir, "ios");
  if (!(await fs.pathExists(iosDir))) {
    return [];
  }

  const plistPaths = await collectInfoPlistPaths(iosDir);
  const updatedPaths: string[] = [];
  for (const plistPath of plistPaths) {
    const current = await fs.readFile(plistPath, "utf8");
    const updated = injectInfoPlistBlock(current, vars);
    if (updated !== current) {
      await fs.writeFile(plistPath, updated, "utf8");
      updatedPaths.push(plistPath);
    }
  }

  return updatedPaths;
}

export async function writeRuntimeEnvExports(
  projectDir: string,
  envName: string,
  vars: Record<string, string>
): Promise<{
  runtimeTsPath: string;
  runtimeEnvFilePath: string;
  runtimeWrapperPath: string;
  androidJsonPath?: string;
  androidXmlPath?: string;
  iosInfoPlistPaths: string[];
}> {
  const runtimeDir = path.join(projectDir, ".rnbuild");
  await fs.ensureDir(runtimeDir);

  const runtimeTsPath = path.join(projectDir, "rnbuild.env.ts");
  const tsContent =
    "// Auto-generated by react-native-build-orchestrator. Do not edit manually.\n" +
    `export const RNBuildEnv = ${JSON.stringify(vars, null, 2)} as const;\n` +
    "export type RNBuildEnvKey = keyof typeof RNBuildEnv;\n" +
    "export default RNBuildEnv;\n";
  await fs.writeFile(runtimeTsPath, tsContent, "utf8");

  const runtimeWrapperPath = path.join(projectDir, "src", "config", "env.ts");
  await fs.ensureDir(path.dirname(runtimeWrapperPath));
  const relativeImportPath = path
    .relative(path.dirname(runtimeWrapperPath), runtimeTsPath)
    .replace(/\\/g, "/")
    .replace(/\.ts$/, "");
  const importPath = relativeImportPath.startsWith(".")
    ? relativeImportPath
    : `./${relativeImportPath}`;
  const wrapperContent =
    "// Auto-generated by react-native-build-orchestrator. Import this file in your app code.\n" +
    `import RNBuildEnv from \"${importPath}\";\n` +
    `export { RNBuildEnv };\n` +
    `export type { RNBuildEnvKey } from \"${importPath}\";\n` +
    "const Config = RNBuildEnv;\n" +
    "export default Config;\n";
  await fs.writeFile(runtimeWrapperPath, wrapperContent, "utf8");

  const runtimeEnvFilePath = path.join(runtimeDir, "active.env");
  const envLines = Object.entries(vars)
    .filter(([key]) => key !== "ENVFILE")
    .map(([key, value]) => `${key}=${JSON.stringify(value)}`);
  await fs.writeFile(runtimeEnvFilePath, `${envLines.join("\n")}\n`, "utf8");

  const androidArtifacts = await writeAndroidNativeEnv(projectDir, vars);
  const iosInfoPlistPaths = await writeIosNativeEnv(projectDir, vars);

  return {
    runtimeTsPath,
    runtimeEnvFilePath,
    runtimeWrapperPath,
    androidJsonPath: androidArtifacts?.androidJsonPath,
    androidXmlPath: androidArtifacts?.androidXmlPath,
    iosInfoPlistPaths
  };
}